name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4


      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: olayinkaadebisi/fastapiwithnginx:latest